### ISSUE TITLE
Error with listbox control 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshprotools#1]
![](https://files.gitter.im/ironmansoftware/help/PuUl/image.png)

```
$listBox1.FormattingEnabled = $true
$listBox1.ItemHeight = [System.Int32]37
$listBox1.Items.AddRange([System.Object[]]@([string]'General User Information',[string]'Mailbox Type',[string]'Mailbox Size'))
$listBox1.Location = (New-Object -TypeName System.Drawing.Point -ArgumentList @([System.Int32]804,[System.Int32]67))
$listBox1.Name = [string]'listBox1'
$listBox1.Size = (New-Object -TypeName System.Drawing.Size -ArgumentList @([System.Int32]374,[System.Int32]300))
$listBox1.TabIndex = [System.Int32]0
```

**Comment by nati0** [comment]
Hi Adam, i submitted the material you listed this bug with.
I thougt I'd chip in with what i found, in my quest for a solution to the problem.
Several C# Developers seem to believe that the issue occurs with the attempt to run controls made with 32bit code, with a 64bit processor. If this information is useful to you, i don't know. I didn't know what to do with it.
