### ISSUE TITLE
EXE Version Not Correct on packaged executable.

### ISSUE THREAD

**Issue by adam-birds-hwt** [ironmansoftware/poshprotools#17]
Hi, I have a WPF Project, with about 10 files.
I have set the version number in the project properties as well as author and company.
But the built executable. I have tested building as release or debug but none of the details are showing the EXE. See below screenshots.
![image](https://user-images.githubusercontent.com/36477553/40168980-d021f694-59bc-11e8-85b9-510f2a1574bf.png)
![image](https://user-images.githubusercontent.com/36477553/40169041-f8946670-59bc-11e8-9a90-93dfb896f707.png)
Please can you advise, unsure if I am doing it wrong or something or whether its a bug.

**Comment by adamdriscoll** [comment]
The options for Versioning executables are coming in the 1.5.0 release that should be out today or tomorrow. It's separate setting from the module settings.
