### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by kmroan** [ironmansoftware/poshprotools#20]
I am working on a wpf GUI tool using posh pro tools / visual studio 2017, and I'm wondering if there is a way to specify an icon for your application? Everything i have come across on google is for c#/wpf applications. 

I can set the <window> icon, but that does not affect the executable that is created when I build the project.

**Comment by kmroan** [comment]
I cannot edit the original comment, but I can set the icon on the WPF window, but that does not set the icon for the executable created when the project is built.

**Comment by Ambre00** [comment]
I agree ! could you add this feature quickly ?

**Comment by adamdriscoll** [comment]
This has been resolved and will be in the 1.6 release that will be out in a few days.
