### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by StitchTech** [ironmansoftware/poshprotools#37]
ProTools were working in VS Code perfectly until I had to rebuild my hard drive. Now, with new install, I'm getting error messages:

`
PS C:\Users\dkoppy\Scripts> Import-Module C:\Users\dkoppy\.vscode\extensions\ironmansoftware.powershellprotools-0.1.3\out\Import-PoshProTools.ps1
Import-Module : The specified module 'C:\Users\dkoppy\.vscode\extensions\ironmansoftware.powershellprotools-0.1.3\out\Import-PoshProTools.ps1' was not loaded because no valid module file
was found in any module directory.
At line:1 char:1
+ Import-Module C:\Users\dkoppy\.vscode\extensions\ironmansoftware.powe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\dkoppy...oshProTools.ps1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\Users\dkoppy\Scripts> Get-PoshProToolsLicense | Select-Object -ExpandProperty Status | Out-PoshProToolsPipe -PipeName '1a0d7180-e0f8-11e8-9990-cf2a30234877'
Out-PoshProToolsPipe : The term 'Out-PoshProToolsPipe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:66
+ ... | Select-Object -ExpandProperty Status | Out-PoshProToolsPipe -PipeNa ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Out-PoshProToolsPipe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

I've installed the module for AllUsers because I use a different default modules folder on my development machine.  I've tried uninstalling, wiping the extension from the .vscode directory, manual install. Any ideas what's wrong here?

**Comment by adamdriscoll** [comment]
This has been resolved in the 0.1.4 version of the extension. Sorry for the issue.
