### ISSUE TITLE
"Try Now" link on https://poshtools.com/powershell-pro-tools/ takes you to PowerShell Tools page

### ISSUE THREAD

**Issue by billcharlton0028** [ironmansoftware/poshprotools#38]
On the page https://poshtools.com/powershell-pro-tools/, the "Try Now" link at the bottom of the page navigates to the "PowerShell Tools" (i.e., not Pro) page at https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561

**Comment by adamdriscoll** [comment]
This is expected. The pro tools are now integrated into PoshTools. More info here: https://docs.poshtools.com/release-notes/4.0
